name: Autofast - staging CI

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
        
    - run: npm run build --if-present
    - run: cd ../../build/
    - run: npm ci --production
    
