name: Autofast - staging CI

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'

    - name: Instalando dependencias
    - run: npm install

    - name: Gerando build
    - run: npm run build --if-present

    - name: Instalando dependencias de produção
    - run: cd ../../build/
    - run: npm ci --production
